steps:
    #Pulling cache from the last build. If not available, just exit normally
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull gcr.io/$PROJECT_ID/rotwebserver:latest || exit 0']

    #Build with cache found
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build',
           '-t', 'gcr.io/$PROJECT_ID/rotwebserver:latest',
           '--cache-from', 'gcr.io/$PROJECT_ID/rotwebserver:latest',
           '-f', 'Dockerfile',
           '.']
    #push image to register
images:
    - 'gcr.io/$PROJECT_ID/rotwebserver:latest'
