steps:
    #Step 1 -> Pull the builder from the registry container
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull gcr.io/$PROJECT_ID/rotwebserver:builder || exit 0']

    #Step 2 -> Rebuild the builder, using the cached from last build
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build',
            '-t', 'gcr.io/$PROJECT_ID/rotwebserver:builder',
            '--target', 'builder',
            '--cache-from', 'gcr.io/$PROJECT_ID/rotwebserver:builder',
            '-f', 'Dockerfile',
            '.']

    #Step 3 -> Store the new builder image in the Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/rotwebserver:builder']

    #Step 4 -> Build the runtime image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build',
           '-t', 'gcr.io/$PROJECT_ID/rotwebserver:latest',
           '--cache-from', 'gcr.io/$PROJECT_ID/rotwebserver:builder',
           '-f', 'Dockerfile',
           '.']

    #Step 5 -> Deploy Image
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [ 'run',
            'deploy', 'rotwebserver',
            '--image', 'gcr.io/$PROJECT_ID/rotwebserver:latest',
            '--region', 'us-central1' ]

    #Make the image made last step available after the build
images:
    - 'gcr.io/$PROJECT_ID/rotwebserver:latest'

timeout: 1800s